name: hlarchical
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - setuptools=80.9.0
  - numpy=2.3.5
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - pandas=2.3.3
  - PyYAML=6.0.3
  - scikit-learn=1.8.0
  - joblib=1.5.1
  - plink=1.90b7.7
  - plink2=2.0.0a.6.9
  - bcftools=1.22
  - beagle=5.5_27Feb25.75f
  - openpyxl=3.1.5
  - pip
  - pip:
      - -r requirements.txt
      - -e . 
